#!/bin/bash

# Var declaration
user_dir="/home/"$(whoami)
connections_file=$user_dir"/.config/rsshync/connections"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Initialization
mkdir -p $user_dir"/.config/rsshync/"
touch $connections_file


## FUNCTIONS ##
function help_menu() {
  echo
  echo -e "\t rsshync commands: \n"
  echo -e "\t\t --help       Displays this page of commands"
  #echo -e "\t\t --help-eg    Displays a list of example commands"
  #echo -e "\t\t --status     Checks the ssh status of a connection"
  #echo -e "\t\t --add        Add a rsshync connection: rsshync --add [HOST@ADDRESS] {PORT}"
  #echo -e "\t\t a"

  echo -e "\t\t Current use: rsshync /path/to/dir [HOST@ADDRESS] {PORT}"
  echo

  return 0
}
function install_packages() {
  echo "Installing packages"
  if [[ ! -z $(which yay) ]]; then
    yay -S --noconfirm rsync openssh   
  elif [[ ! -z $(which pacman) ]]; then
    sudo pacman -S --noconfirm rsync openssh   
  elif [[ ! -z $(which apt) ]]; then
    sudo apt install -y rsync openssh   
  fi
}
function add_connections() {
  if [[ -z $1 ]]; then exit; fi
  while read -r LINE; do
    if [[ $1 == $LINE ]]; then
      echo -e "$LINE already added to connections file";
      return;
    fi
  done < $connections_file
  test_ssh $1 
  err_code=$?
  if [[ $err_code == 0 ]]; then
    echo "Connection to $1 was successful, adding to your list of connections"
    no_duplicates $1
  else
    echo "Connection to $1 failed, make sure your address, host, and port are all correct. E.G. USER@IP_ADDRESS:PORT"
  fi
}

function test_ssh() {
  if [[ "$1" =~ "@" ]]; then
    HOST=$(echo "$1" | sed 's/@.*//')
    echo $HOST
  fi
  ADDR=$(echo "$1" | sed 's/^.*@//' | sed 's/:.*//')
  echo $ADDR
  if [[ "$1" =~ ":" ]]; then
    PORT=$(echo "$1" | sed 's/^.*://')
    echo $PORT
  fi

  if [[ ! -z $PORT ]]; then
    ssh -q -p $PORT $HOST$ADDR exit
  else
    ssh -q $HOST$ADDR exit
  fi
  return $?
}

function no_duplicates() {
  array=()
  while read -r LINE; do
    if [[ $1 == $LINE  || $LINE == "LIST OF CONNECTIONS" ]]; then
      continue;
    fi
    array+=("$LINE")
  done < $connections_file
  array+=("$1")
  echo "LIST OF CONNECTIONS" > $connections_file
  for connection in "${array[@]}"; do
    echo $connection >> $connections_file
  done
}

function status_of_connections() {
  connections_arr=() # I have to make a array for this rather than just reading the file or else I get race conditions
  while read -r LINE; do
    if [[ ! $LINE == "LIST OF CONNECTIONS" ]]; then
      connections_arr+=($LINE)
    fi
  done < $connections_file

  if [[ ${#connections_arr[@]} == 0 ]]; then
    echo "No connections are currently added"
    exit;
  fi
  echo -e "-------------------------------------" 
  for LINE in "${connections_arr[@]}"; do
    test_ssh $LINE
    if [[ $? == 0 ]]; then
      echo -e "\t $LINE connection ${GREEN}OK${NC}"
    else
      echo -e "\t $LINE connection ${RED}BAD${NC}"
    fi
  done
  echo -e "-------------------------------------" 
}

function delete_connections() {
  if [[ -z $1 ]]; then exit; fi
  array=()
  check_delete=0
  while read -r LINE; do
    if [[ $LINE == "LIST OF CONNECTIONS" ]]; then
      continue;
    elif [[ $1 == $LINE ]]; then
      check_delete=1
      continue;
    fi
    array+=("$LINE")
  done < $connections_file

  if [[ "${#array[@]}" == "0" && $check_delete == 0 ]]; then
    echo "Your list of connections is currently empty"
    exit;
  fi

  echo "LIST OF CONNECTIONS" > $connections_file
  for connection in "${array[@]}"; do
    echo $connection >> $connections_file
  done

  if [[ $check_delete == 1 ]]; then
    echo "Deleted $LINE from connections\n"
    echo -e "New list of connections"
    list_connections
  else
    echo "No connection was deleted"
  fi
}


function set_connections() {
  connection_array=()
  selected_connections=()
  if [[ $1 == "all" ]]; then
    while read -r LINE; do
      if [[ $LINE == "LIST OF CONNECTIONS" ]]; then
        continue;
      fi
      selected_connections+=("$LINE")
    done < $connections_file
  else
    while read -r LINE; do
      if [[ $LINE == "LIST OF CONNECTIONS" ]]; then
        continue;
      fi
      connections_array+=("$LINE")
    done < $connections_file
    echo -e "\nSelect connections you want to backup to:"
    list_connections_numbered
    read -p "Connection #: " uinput
    while [[ ! -z $uinput ]]; do
      selected_ip="${connections_array[$(( uinput-1 ))]}"
      local balls=$(check_if_in_array $selected_ip)
      if [[ $balls == 0 ]]; then
        selected_connections+=("$selected_ip")
      else
        selected_connections=("${selected_connections[@]/$selected_ip}")
      fi
      list_connections_numbered
      read -p "Connection #: " uinput
    done
  fi

}

function list_connections() {
    echo -e "-------------------------------------" 
    while read -r LINE; do
      if [[ $LINE == "LIST OF CONNECTIONS" ]]; then
        continue;
      fi
      array+=("$LINE")
    done < $connections_file
    for item in "${array[@]}"; do
      echo $item
    done
    echo -e "-------------------------------------" 
}

function check_if_in_array() {
    for i in $(seq 0 $(( ${#selected_connections[@]}-1 ))); do
      if [[ "$1" == "${selected_connections[i]}" ]]; then
        echo 1
        return
      fi
    done
    echo 0
    return
}

function list_connections_numbered() {
    echo -e "-------------------------------------" 
    for i in $(seq 0 $(( ${#connections_array[@]}-1 ))); do
      mark=0
      for selected in "${selected_connections[@]}"; do
        if [[ "$selected" == "${connections_array[i]}" ]]; then
          mark=1
        fi
      done
      
      num=$(( i+1 ))
      if [[ $mark -eq 1 ]]; then
        echo -e "$num.\t ${GREEN}${connections_array[i]}${NC}"
      else
        echo -e "$num.\t ${connections_array[i]}"
      fi
    done
    echo -e "-------------------------------------" 
}
