#!/bin/bash

# Var declaration
VERSION="1.0.1"
user=$(whoami)

source functions

if [[ -z $(which ssh) || -z $(which rsync) ]]; then 
  echo "The required pacakges are not installed (rsync, openssh)"
  read -p "Would you like to automcatically install the packages? [Y/n]: " uinput 
  if [[ -z $uinput || $uinput == "n" || $uinput == "N" ]]; then 
    install_packages
  fi
fi

if [[ -z $1 ]]; then 
  help_menu
fi

#Lists the different options that the user can choose from, "hmast" is for individual letters options like "-h" and "-m"
options=$(getopt -o hasdv,help,add,status,set,scope,delete,version --long "help,status,set,scope,delete,version" -- "$@")
[ $? -eq 0 ] || {
    echo "Incorrect options provided"
    exit 1
}
eval set -- "$options"
while true; do
    case "$1" in
      -h | -help | --help)
          help_menu
          exit;;
      -v | -version | --version)              #Will display current version)
          shift;
          echo $VERSION
          exit;;
      -a | -add | --add)
          shift;
          shift;
          add_connections $1
          exit;;
      -s | -status | --status)				          
          shift;	            
          status_of_connections
          exit;;
      -d | -delete | --delete)				          
          shift;	            
          shift;	            
          #if [[ -z $1 ]]; then
          #  echo "Please make sure to add the connection(s) you want to delete";
          #  exit;
          #fi
          while true; do
            delete_connections $1
            if [[ -z $1 ]]; then
              echo "Please make sure to add the connection(s) you want to delete";
              exit;
            fi
            shift;	            
          done
          exit;;
      -set | --set)				          
          shift;	            
          shift;	            
          set_connections $@
          exit;;
      -scope | --scope)				          
          shift;	            
          shift;	            
          scope_connections
          exit;;
      --)
          shift
          #echo "Invalid option"
          break
        ;;
    esac
    shift
done

